swagger: '2.0'
info:
  description: "Project of Alterra Academy"
  version: 1.0.0
  title: "MyTaskApp"
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /BentarRaharja/MyTaskAppBe20/1.0.0
securityDefinitions:
  JWTAuth:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: "Use Token"
# schemes:
#   - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /login:
    post:
      summary: Login
      tags:
        - Login
      operationId: Login
      deprecated: false
      produces:
        - application/json; charset=UTF-8
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: Authorization
          in: header
          required: false
          default: Bearer {token}
          type: string
        - name: email
          in: formData
          required: true
          type: string
          description: ''
        - name: password
          in: formData
          required: true
          type: integer
          format: int32
          description: ''
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Login'
          examples:
            application/json; charset=UTF-8:
              message: success login
              data:
                nama: bentar
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MDQ2MjgzMDQsInVzZXJJZCI6MX0.zmcb-PCZLGjE8aTgwLE8rIcJlJRZb64Ex3VZBT-2F_0
          headers:
            Vary:
              type: string
              default: Origin
            Date:
              type: string
              default: Sun, 07 Jan 2024 10:51:44 GMT
            Content-Length:
              type: string
              default: '208'
  /users:
    post:
      summary: Register
      tags:
        - Users
      operationId: Register
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: Authorization
          in: header
          required: false
          default: Bearer {token}
          type: string
        - name: name
          in: formData
          required: true
          type: string
          description: ''
        - name: email
          in: formData
          required: true
          type: string
          description: ''
        - name: password
          in: formData
          required: true
          type: integer
          format: int32
          description: ''
        - name: address
          in: formData
          required: true
          type: string
          description: ''
        - name: phone_number
          in: formData
          required: true
          type: string
          description: ''
        - name: role
          in: formData
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
    get:
      summary: Fetch By User Id Login
      tags:
        - Users
      operationId: FetchByUserIdLogin
      deprecated: false
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      security: 
        - JWTAuth: []
    put:
      summary: Update User
      tags:
        - Users
      operationId: UpdateUser
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: name
          in: formData
          required: true
          type: string
          description: ''
        - name: email
          in: formData
          required: true
          type: string
          description: ''
        - name: password
          in: formData
          required: true
          type: integer
          format: int32
          description: ''
        - name: address
          in: formData
          required: true
          type: string
          description: ''
        - name: phone_number
          in: formData
          required: true
          type: string
          description: ''
        - name: role
          in: formData
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
      security: 
        - JWTAuth: []
    delete:
      summary: Delete User
      tags:
        - Users
      operationId: DeleteUser
      deprecated: false
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      security: 
        - JWTAuth: []
  /projects:
    post:
      summary: Post Project
      tags:
        - Projects
      operationId: PostProject
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: name
          in: formData
          required: true
          type: string
          description: ''
        - name: description
          in: formData
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
      security: 
        - JWTAuth: []
    get:
      summary: Fetch All Projects
      tags:
        - Projects
      operationId: FetchAllProjects
      deprecated: false
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      security: 
        - JWTAuth: []
  /projects/{id}:
    get:
      summary: Fetch By Id Project
      tags:
        - Projects
      operationId: FetchByIdProject
      deprecated: false
      produces:
        - application/json
      parameters: 
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: ''
          headers: {}
      security: 
        - JWTAuth: []
    put:
      summary: Update Project
      tags:
        - Projects
      operationId: UpdateProject
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
        - name: name
          in: formData
          required: true
          type: string
          description: ''
        - name: description
          in: formData
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
      security: 
        - JWTAuth: []
    delete:
      summary: Delete Project
      tags:
        - Projects
      operationId: DeleteProject
      deprecated: false
      produces:
        - application/json
      parameters: 
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: ''
          headers: {}
      security: 
        - JWTAuth: []
  /tasks:
    post:
      summary: Post Task
      tags:
        - Tasks
      operationId: PostTask
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: name
          in: formData
          required: true
          type: string
          description: ''
        - name: project_id
          in: formData
          required: true
          type: integer
          format: int32
          description: ''
        - name: description
          in: formData
          required: true
          type: string
          description: ''
        - name: status_task
          in: formData
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
      security: 
        - JWTAuth: []
  /tasks/{id}:
    put:
      summary: Update Task
      tags:
        - Tasks
      operationId: UpdateTask
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
        - name: name
          in: formData
          required: true
          type: string
          description: ''
        - name: description
          in: formData
          required: true
          type: string
          description: ''
        - name: status_task
          in: formData
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
      security: 
        - JWTAuth: []
    delete:
      summary: Delete Task
      tags:
        - Tasks
      operationId: DeleteTask
      deprecated: false
      produces:
        - application/json
      parameters: 
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: ''
          headers: {}
      security: 
        - JWTAuth: []
definitions:
  Login:
    title: Login
    example:
      message: success login
      data:
        nama: bentar
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MDQ2MjgzMDQsInVzZXJJZCI6MX0.zmcb-PCZLGjE8aTgwLE8rIcJlJRZb64Ex3VZBT-2F_0
    type: object
    properties:
      message:
        type: string
      data:
        $ref: '#/definitions/Data'
    required:
      - message
      - data
  Data:
    title: Data
    example:
      nama: bentar
      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MDQ2MjgzMDQsInVzZXJJZCI6MX0.zmcb-PCZLGjE8aTgwLE8rIcJlJRZb64Ex3VZBT-2F_0
    type: object
    properties:
      nama:
        type: string
      token:
        type: string
    required:
      - nama
      - token
# Added by API Auto Mocking Plugin
schemes:
 - https
 - http